### ISSUE TITLE
instance (Floating a) => Precise (Log a)

### ISSUE THREAD

**Issue by dmcclean** [ekmett/log-domain#25]
There's an old libraries list proposal (https://mail.haskell.org/pipermail/libraries/2014-April/022667.html) (which seems to have died a quiet death) where @ekmett argues (correctly IMO) for moving `log1p` and friends into `Floating` with default definitions, on the theory that `log1p` is definable for every floating thing, even if you can't implement it with more precision than you would get by splitting it into an addition and a log.

By that reasoning, shouldn't there be a valid `instance (Floating a) => Precise (Log a)`?

AFAIK you'd be stuck with this implementation:

````
instance (Floating a) => Precise (Log a) where
  log1p x = log $ 1 + x
  expm1 x = exp x - 1
````

Relatedly, if those would be acceptable default definitions under the proposal to move them into `Floating`, shouldn't they still be acceptable default definitions while they are in exile in `Precise`? In which case I would argue for adopting them as defaults and just having:

````
instance (Floating a) = Precise (Log a) where
````

**Comment by ekmett** [comment]
When the new combinators get old enough that we can dump support for old ghc versions then Precise will go away entirely.

We made the class precisely, no pun intended, because we needed the precision here, though!

Yes, those definitions suffice when nothing else is available, but they are much much worse than the accuracy optimized ones that is the very reason for the existence of this class and the eventual move into Floating.

I'd hazard that in a couple of years once the ghc 8 Floating improvements have 3 releases of support we can kill Precise. -- or we could change to the weaker signature only on newer ghcs earlier.

**Comment by ekmett** [comment]
I'm going to close this issue as the downgrade would be far far too sharp, and seems exactly backwards from the desired goal.

**Comment by ekmett** [comment]
Or am I misparsing you somehow? Feel free to reopen if that is the case.

**Comment by dmcclean** [comment]
Are you saying that they are moving to `Floating` in GHC 8?
If so I was unaware of that and my suggestion is indeed bad.

**Comment by ekmett** [comment]
Indeed, I am. :)

**Comment by dmcclean** [comment]
OK, in that case, thanks again for your great work. It's awesome that you pushed that through.

Sorry for the noise. I tried to look for the GHC trac case but I must not have tried hard enough.

**Comment by ekmett** [comment]
Note: The ghc version has default definitions at least for a transition period, but we may drop them eventually after a log enough burn in period and a warning window.

The defaults can't be removed before 8.8, though, and we haven't committed one way or the other to removing them.
